version: '3'
     
services:
  django: &django
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    image: django_auto-datatables
    container_name: django_auto-datatables
    working_dir: /app
    volumes:
      - ./:/app:z
    ports:
      - "8000:8000"
    command: ./docker/django
    # entrypoint: "tail -f /dev/null"

  docs:
    <<: *django
    image: django_auto-datatables_docs
    container_name: django_auto-datatables_docs
    working_dir: /app/docs
    volumes:
      - ./:/app:z
    ports:
      - "9000:9000"
    command: ../docker/docs
    # entrypoint: "tail -f /dev/null"
